server:
  port: 8090

spring:
  servlet:
    encoding:
      force-response: true

  output:
    ansi:
      enable: always

  datasource:
    url: jdbc:mysql://localhost:3306/my_news?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    cache: false


